### ISSUE TITLE
Typo in repo description: builodut

### ISSUE THREAD

**Issue by jean** [collective/plone.recipe.varnish#18]
```diff
- Install and/or configure varnish from builodut
+ Install and/or configure varnish from buildout
```

**Comment by mauritsvanrees** [comment]
I don't see this typo in the source code anymore, at least not on master, so looks like this was fixed.

**Comment by mauritsvanrees** [comment]
Ah, I was only looking in the code, but you meant the description of the github repo. I have fixed this now. Thanks.
