### ISSUE TITLE
2.0a1, vcl, round-robin versus round_robin

### ISSUE THREAD

**Issue by noobulous** [collective/plone.recipe.varnish#24]
Salutations, thanks for your time.

I'm using 2.0a1 with varnish 4.0.2, my configuration section specifies balancer = round-robin, which is what ends up in the generated VLC. varnish, I think, is looking for round_robin instead.

Symbol not found: 'directors.round-robin' at ('input' Line 44 Pos 22)
    new balancer_0 = directors.round-robin();
---------------------#####################---

If I edit the generated VCL and replace round-robin with round_robin it works.

**Comment by pbauer** [comment]
I can confirm this.

**Comment by cleberjsantos** [comment]
:+1:  The error is here https://github.com/collective/plone.recipe.varnish/blob/master/plone/recipe/varnish/vclgen.py#L20

**Comment by cleberjsantos** [comment]
Fixed on pull request #36
