### ISSUE TITLE
error on example backend

### ISSUE THREAD

**Issue by parruc** [collective/plone.recipe.varnish#33]
using the example backend:

/VirtualHostBase/http/${nginx:host}:80/Plone:127.0.0.1:8086

I get "Invalid syntax for backend" error.

The error looks quite obvious to me but I dont know the possible implication so I'm not opening a pull request.

in plone/recipe/varnish/recipe.py:170
`def _process_backends(self):
        result = []
        raw_backends = [
            _.rsplit(':', 3)
            for _ in self.options['backends'].strip().split()
        ]
`

I replaced rsplit(':', 3) with rsplit(':', 2) cause I'm expecting at most 3 values so I have to split at most 2 times

**Comment by agitator** [comment]
which version are you using?
i think this was fixed with https://github.com/collective/plone.recipe.varnish/commit/e8a95030419097c196b961dbf1c0a8106b584958

**Comment by parruc** [comment]
That's exactly it.

sorry but seeing the dev0 in the version name 2.0a4.dev0 I've used the last non-dev one ( 2.0a3 )
