### ISSUE TITLE
'cookies for pass' parsing query string, causes Plone theme editor to break

### ISSUE THREAD

**Issue by instification** [collective/plone.recipe.varnish#42]
# Problem

The default implementation of the recipe creates a 'cookies for pass' section that strips session coookies etc for urls that end in js, css and kss 

```
/* cookies for pass */
    if (req.http.Cookie && req.http.Cookie ~ "__ac(|_(name|password|persistent))=") {
        if (req.url ~ "\.(js|css|kss)") {
            unset req.http.cookie;
            return(pipe);
        }
        return(pass);
    }
```

However, `req.url` includes the query string.

The Plone theme editor opens css files using the following xhr request:

```
/@@plone.resourceeditor.filemanager-actions?action=getFile&path=%2Fstylesheets%2Ffonts.css
```

Varnish is stripping the cookie and therefore Plone redirects to the `require_login` page, causing the css to open without any contents in the theme editor ide.

# Possible solutions

 - Sanitise the `req.url` variable prior to testing for js/css/kss - something like - `set req.url = regsub(req.url, "\?.*$", "");` (courtesy of https://varnish-cache.org/lists/pipermail/varnish-misc/2011-April/020419.html)
 - Don't unset cookies for xhr requests. e.g. changing https://github.com/collective/plone.recipe.varnish/blob/master/plone/recipe/varnish/templates/varnish4.vcl.jinja2#L136 to `if (req.http.Cookie && req.http.Cookie ~ "{{rule['match']}} && req.http.X-Requested-With != "XMLHttpRequest"") { `

**Comment by mauritsvanrees** [comment]
The PR got merged, so I close this.
