### ISSUE TITLE
custom vcl_fetch code is never injected into jinja template

### ISSUE THREAD

**Issue by petschki** [collective/plone.recipe.varnish#45]
documentation claims to insert arbitrary code into template but this isn't implemented for `vcl_fetch`

**Comment by petschki** [comment]
ah ... just saw, that there are two undocumented custom parameters `vcl_backend_fetch` and `vcl_backend_response` which can be used instead of `vcl_fetch`

**Comment by jensens** [comment]
Do you mind to update the documentation?
