### ISSUE TITLE
Simplify: no longer test with different Plone versions

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/plone.recipe.varnish#69]
Currently, the repository has a `plone-4.3.x.cfg` and `plone-5.0.x.cfg` that only differ in which versions.cfg file from dist.plone.org they are loading. The versions are outdated a bit: 4.3.10 and 5.0.5.

But only very few versions are actually needed by the recipe buildout config. When I print the picked versions, and compare what is printed with and without loading the Plone versions file, I am only missing pins for these:

```
Jinja2 = 2.10
collective.recipe.omelette = 0.16
zc.recipe.egg = 2.0.7
zc.recipe.testrunner = 2.0.0
decorator = 4.4.0
zope.exceptions = 4.3
zope.interface = 4.6.0
zope.testrunner = 5.0
```

On Travis we are testing both 4.3 and 5.0, but that seems unneeded, as there will hardly be differences in versions.

So I propose that we simplify the build by removing the 4.3/5.0 configs and just using a `buildout.cfg`.  I can do that.
Possibly we could let Travis do one build with all versions pinned, and have a second build where we pin nothing, so we can see if any errors pop up with latest versions.  We could allow this second build to fail.

What do you think?
cc @jensens @fredvd @cleberjsantos

**Comment by cleberjsantos** [comment]
@mauritsvanrees +1 Yes, I think it would be the best way :)

**Comment by jensens** [comment]
@mauritsvanrees +1 too
