### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/plone.recipe.varnish#73]
Just quickly testing with current master.
On Python 3, `bin/test` fails with a `ModuleNotFoundError` because `test_recipe.py` imports `commands`, which is no longer there on Python 3. So we will likely need `subprocess.check_output`. Should be relatively straightforward.

I leave the tests behind for the moment, and simply try the recipe in a Python 3 buildout. Simply this in a buildout config (added to the `buildout.cfg` of the recipe now):

```
[varnish-build]
recipe = plone.recipe.varnish:build
```

And then:

```
$ bin/buildout install varnish-build
...
Making all in varnishd
/Users/maurits/community/plone.recipe.varnish/bin/python ../../lib/libvcc/vsctool.py -ch ./main.vsc
/Users/maurits/community/plone.recipe.varnish/bin/python ../../lib/libvcc/vsctool.py -ch ./lck.vsc
  CC       vhp_gen_hufdec-vhp_gen_hufdec.o
/Users/maurits/community/plone.recipe.varnish/bin/python ../../lib/libvcc/vsctool.py -ch ./lck.vsc
Traceback (most recent call last):
  File "../../lib/libvcc/vsctool.py", line 40, in <module>
    import StringIO
ModuleNotFoundError: No module named 'StringIO'
Traceback (most recent call last):
  File "../../lib/libvcc/vsctool.py", line 40, in <module>
    import StringIO
ModuleNotFoundError: No module named 'StringIO'
Traceback (most recent call last):
  File "../../lib/libvcc/vsctool.py", line 40, in <module>
    import StringIO
ModuleNotFoundError: No module named 'StringIO'
```

So it seems the default varnish 4 version we use, is not compatible with Python 3.
Tried with varnish 5.2.1 as well, same problem.

Actually, I now get the same error even in a Python 2 buildout, because the default `python` on my system is Python 3, and that is what the `./configure` finds. Activating the Python 2 virtualenv fixes it.

In the 6.2.0 docs it says under the header [Changes for developers and VMOD authors](http://varnish-cache.org/docs/6.2/whats-new/changes-6.2.html?highlight=python#changes-for-developers-and-vmod-authors): "Python tools that generate code now require Python 3." So I guess the `ModuleNotFoundError` will go away with varnish 6.

Fine, I try varnish 6.2.0:

```
$ cat buildout.cfg
...
[varnish-build]
recipe = plone.recipe.varnish:build
url = http://varnish-cache.org/_downloads/varnish-6.2.0.tgz
$ bin/buildout install varnish-build
...
checking for sphinx-build... no
checking for sphinx-build-3.6... no
checking for sphinx-build-3... no
configure: error: sphinx-build is needed to build Varnish, please install python3-sphinx.
```

So it fails due to a missing sphinx, which is likely only needed for the documentation.
This is on Mac.
Tried with 6.1.1 and 6.0.3, same result.

Okay, a quick `bin/pip install sphinx` fixes this. (Actually, I see that Fred added an option for skipping the building of documentation in PR #67. Or rather, this is already supported because we inherit from `zc.recipe.cmmi`: `extra_options = --with-sphinx-build=false`.)

The resulting varnish-script, if I add the two other sections from our `README.txt`, does not yet work:

```
$ bin/varnish-script 
Error:
Message from VCC-compiler:
Expected return action name.
('/Users/maurits/community/plone.recipe.varnish/parts/varnish-configuration/varnish.vcl' Line 159 Pos 13)
    return (miss); # Dead code, keep as a safeguard
------------####-----------------------------------

Running VCC-compiler failed, exited with 2
VCL compilation failed
```

I get the same error on Python 2.
So there is still a bit of work needed. :-)

**Comment by fredvd** [comment]
The return (miss) Is I think a syntax / state machine change in the Varnish VCL  introduced in 6.1 or 6.2, it's not python2/python3 related.

**Comment by fredvd** [comment]
Fixed after the varnish template cleanup and release of the 6.0.0bX versions.  We're running plone.recipe.varnish in production now with python3.7 buildouts.
