### ISSUE TITLE
Streaming

### ISSUE THREAD

**Issue by jensens** [collective/plone.recipe.varnish#87]
I just stumbled over problems with streaming files with our setup. 
We may want to consider configuring something in a direction as described here. 

https://www.getpagespeed.com/server-setup/varnish-static-files-stream

Maybe different than there, Header controlled or so, details to be figured out.

**Comment by fredvd** [comment]
@jensens  I just stumbled over this fix from Maurits from January where  *.mp4 files where not correctly piped .  

Making a 6.0.10 relese now with this fix and Varnish 6.0.10 security release as default
