### ISSUE TITLE
Generate stable VCL

### ISSUE THREAD

**Issue by jean** [collective/plone.recipe.varnish#9]
Currently if you add a backend in the buildout config, the generated VCL will cause noisy diffs, e.g. lots of: 

``` diff
-       .port = "10388";
+       .port = "14312";
```

and

``` diff
-               set req.backend = backend_45;
+               set req.backend = backend_46;
```

One could derive stable ids from domain names, but would be more work to make them valid & unique.

**Comment by iham** [comment]
I guess this is due and past as it is from 2014

please reopen if still valid
